### ISSUE TITLE
As a user, when I share PGP urls I want to see previews on social media, slack or other supported platforms so that the content is more engaging.

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#386] opened 2021-12-02 19:35 UTC
## dev notes
Add opengraph and twitter metadata so that pages will have nice previews (should do this at least for document detail pages and home page; wagtail pages maybe also, but could be a separate issue). Include image preview if associated fragments have images we can use for that.

In mep we have a template include for head metadata; we should adapt from that if it's helpful: https://github.com/Princeton-CDH/mep-django/blob/main/templates/snippets/head_meta.html

We don't have a default social preview image yet, so just omit when we don't have one. (Feel free to add comments about where it would be added.)

For documents with iiif, display the first image as a twitter large image card (similar to mep). 

We could make use of twitter label1/data1 and label2/data2 — I know these are displayed when slack unfurls. For document details page, let's set editor as data1 for now (short version as displayed on document details). Maybe document date could be data2 when we have it.

**Comment by rlskoeser** [comment] 2021-12-03 15:38
@richmanrachel we had different things in mind when we talked about social media previews! I think we'd previously decided we didn't need to embed the twitter feed on the PGP site since it's on the PGL site (although we could revisit that later if desired), so I rewrote this to describe what I thought we were talking about.

**Comment by richmanrachel** [comment] 2021-12-03 15:40
@rlskoeser - I see! This is great. Approve :)

**Comment by rlskoeser** [comment] 2022-03-02 15:00
There's not a good way for anyone else to test these, but I just checked with my browser plugin that simulates opengraph and twitter previews and inspected the metadata being generated in the header on qa. 

Everything looks good generally, but there's one thing we forgot to account for: we need to escape content in a few fields — any content that could contain a quote will break the meta tag and render the preview unreadable. I think this only applies to the description and editor information.

**Comment by rlskoeser** [comment] 2022-03-02 20:57
confirmed fixed in qa

**Closed by rlskoeser** 2022-03-02 20:57 UTC
