### ISSUE TITLE
As a content editor, when I search for tags to add to a document I want the search to ignore case so that I don't create variations of the same tag.

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/geniza#499] opened 2022-01-06 20:28 UTC
## testing notes

- [x] In the admin, find a tag that exists with capital letters, then add that tag—but all lowercase—to a document, and save, and confirm the original tag is added (rather than a new tag being created)
- [x]  confirm tags that previously existed in upper case and lower case variants (e.g., India and india) have been merged correctly (only one tag, all documents associated with that tag, log entry on the tag history documenting the merge)

---

We need to set `TAGGIT_CASE_INSENSITIVE = True` in `base.py` but because tags have already been created, we'll need to collapse existing tags  with a migration before turning this on. A quick script showed that 200 tags were duplicated when made case insensitive, so this shouldn't be done by hand. This work was started in #257.

**Comment by richmanrachel** [comment] 2022-08-11 19:22
I don't think the case sensitivity is totally working, it recommended I add the correct tag but ended up allowing me to save both versions:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/68028846/184222182-877bc3e9-f4f9-4c54-a232-c3b9967a2e95.png">

**Comment by rlskoeser** [comment] 2022-08-11 19:28
@richmanrachel ah, interesting — this maybe a change since Ben wrote up the testing note. I didn't want to force all tags to lower case — for a lot of tags that would result in a loss of information (especially for proper names). 

Does it sound right to you that we should normalize the lowercase version to match the uppercase one if there is already a tag? We don't want to end up with tag variants like this again.

**Comment by richmanrachel** [comment] 2022-08-11 19:31
@rlskoeser - yes, I agree that we should normalize the lowercase to match uppercase!

**Comment by blms** [comment] 2022-08-11 19:33
@rlskoeser I thought that's actually what `TAGGIT_CASE_INSENSITIVE` was supposed to do!

https://github.com/jazzband/django-taggit/blob/eb66e6607bb2997ce63e58c59fdec0df5a474a6b/taggit/managers.py#L220-L231

**Comment by rlskoeser** [comment] 2022-08-12 14:08
@blms thanks for chiming in. I was surprised too. Any idea what's going on? I also see that there are tags that should have been merged but weren't (Formulary / formulary) and the new tag Rachel created didn't get the diacritic stripped — but I tested and `unidecode("mu'ālim")` does return `mu'alim`

**Comment by blms** [comment] 2022-08-15 15:13
> I also see that there are tags that should have been merged but weren't (Formulary / formulary)

This looks right to me, unless one was deleted since you posted this!

![Screen Shot 2022-08-15 at 11 12 28 AM](https://user-images.githubusercontent.com/7234006/184662468-1d4e52c9-2680-4dd2-a47a-f05a9a157ee6.png)

**Comment by blms** [comment] 2022-08-15 15:17
@richmanrachel It looks like that second tag didn't actually get saved. If you do "Save and continue editing" on the document, does that lowercased tag disappear? It does for me! If so, then that's expected behavior. It's ok if it shows up twice in the tags list at first, as long as the duplicates are merged once you save the document.

@rlskoeser Can you find any tags that should have been merged but were not? Formulary looks right to me.

**Comment by rlskoeser** [comment] 2022-08-15 16:03
@blms I'll sync production data to the test site before deploying this again so we can check on a fresh merge.

**Comment by rlskoeser** [comment] 2022-08-16 13:17
@richmanrachel @blms updated the test site with the code update Ben added and a copy of the latest production data. Please test again when you're able.

**Comment by richmanrachel** [comment] 2022-08-16 13:47
It's correcting the tags on the document side and preventing adding tags with the same slug! This is great:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/68028846/184895318-00eb5ddb-741c-47ed-86c1-a3f27130e36a.png">

Closing :)

**Closed by richmanrachel** 2022-08-16 13:47 UTC
Labels: 🆕 enhancement, 🗜️ awaiting testing
