### ISSUE TITLE
In .csv downloads from the admin interface, for joins, the IIIF_url field needs a space after the semicolon.  

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#883] opened 2022-05-21 18:12 UTC
## testing notes

Download a document CSV for some set of records with iiif urls and documents on multiple fragments.

Check that the urls in the iiif_urls field are separated by a space and then a semicolon, and that the urls are clickable and don't include the semicolon in the url.

----

A tiny but annoying thing, which I'm only posting because I assume it's easy to fix:

I downloaded a .csv from the admin interface. One of the rows contains a join. The iiif_url field puts the IIIF urls of all the associated fragments with a semicolon and no space between: 

https://cudl.lib.cam.ac.uk/view/MS-TS-00016-00114;https://cudl.lib.cam.ac.uk/view/MS-TS-00024-00057;;https://cudl.lib.cam.ac.uk/view/MS-TS-AS-00146-00195 
 
Google sheets reads that as a single link and can't parse it. Can the default instead be semicolon followed by space, like this?

https://cudl.lib.cam.ac.uk/view/MS-TS-00016-00114; https://cudl.lib.cam.ac.uk/view/MS-TS-00024-00057; https://cudl.lib.cam.ac.uk/view/MS-TS-AS-00146-00195 

Also for some reason, the second and third URLs are separated by _two_ semicolons. Not sure what's going on there. 

Thanks!

**Comment by rlskoeser** [comment] 2022-10-06 16:16
Downloaded a csv of records with iiif images from the test site and confirmed resolved

**Comment by kseniaryzhova** [comment] 2022-10-18 19:10
@rlskoeser in the production admin, the csv does not have a space and a semicolon between IIIF links. Instead it's a semicolon then space. In the test site admin, the csv just downloads as blank (same data set)

**Comment by kseniaryzhova** [comment] 2022-10-24 18:54
![image](https://user-images.githubusercontent.com/105385128/197599746-68c5a0b5-f3da-4502-b2e2-217b8f2fc73c.png)
confirming that the links are spearated by a space, then a semicolon and another space. But they are still not linkable, not when first opened in Excel.

**Comment by kseniaryzhova** [comment] 2022-10-25 20:03
@rlskoeser closing, because I spoke to Marina and she said this isn't a priority, we can revisit with Performant later.

**Closed by kseniaryzhova** 2022-10-25 20:03 UTC
Labels: 🐛 bug, 🗜️ awaiting testing
