### ISSUE TITLE
Implement designs for public site inferred date filter 

### ISSUE THREAD

**Issue by kseniaryzhova** [Princeton-CDH/geniza#1410] opened 2023-07-04 21:26 UTC
**Describe the solution you'd like**
Based on @gissoo's designs, which Marina approved. We want public site users to be able to search by inferred date and exclude inferred date as well if they wanted to.

**Comment by blms** [comment] 2023-07-10 18:10
Closing as duplicate of https://github.com/Princeton-CDH/geniza/issues/1347.

**Closed by blms** 2023-07-10 18:10 UTC
Labels: 🛠️ chore, performant
