### ISSUE TITLE
As a content editor, I want to create and edit fragment records so that I can document changes in the fragments.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#75] opened 2021-02-16 01:13 UTC
## testing notes
**List display**
- [x] Ensure that fields that you want visible are available
- [x] Test that fragments are searchable by:
  - [x] shelfmark
  - [x] historic shelfark
  - [x] notes
- [x] Test that results for filtering by the following fields operate properly:
  - [x] collection
  - [x] Is a multifragment
  - [x] Has a url

**edit**
- [x] Test that changes to a fragment through the edit display are saved and reflected in the list view.
- [x] Test editing image url on the list view
- [x] Test that fragments with an associated IIIF url display a IIIF viewer with the page images
- [x] Test editing multifragment field

-----
## dev notes

revisions after testing:
- [x] fix multifragment list filter
- [x] fix iiif viewer mixed content error
- [x] make multifragment a boolean field and update admin filter/edit accordingly

**Fields**
Provide a list of the fields to be included on this model.
- Shelfmark
- Old shelfmark
- Library (abbreviation)
- Multi-fragment
- notes
- image url
- IIIF

**List Fields**
Which fields should be included on the django admin list view?
- Shelfmark
- library (abbreviation)
- image url 
- Multi-fragment (boolean)

**Edit Fields**
Which fields should be editable via django admin view? Please list them in the order you want them to appear. Indicate which fields are optional, and any fields that should be displayed but not editable.
- shelfmark
- historical shelfmark (optional) - populated if shelfmark field is changed
- library
- image url (optional)
- image thumbnail
- IIIF
- multi-fragment (optional)
- notes (optional)

**Search Fields**
Which fields should be searchable in the django admin list view?
- shelfmark
- historical shelfmark
- notes

**Default sort**
- Shelfmark

**Filters**
Which fields should be used for list filters?
- Library
- Multi-fragment (boolean)
- Image (boolean)

**List Fields (optional)**
Which fields (if any) should be editable on the django admin list view?
- Image url

**Comment by richmanrachel** [comment] 2021-03-04 22:29
- It's not obvious in the Edit Fragment view that the box for multifragment is supposed to be filled out as "Yes" (I tried it in a test, and it did create a check mark in the right place in the list view, but it wasn't initially clear that this is how that box is supposed to be used. Perhaps a checkbox here would be clearer.
- Filter by Multifragment (Yes/No) didn't work either, perhaps because the boxes referenced in my question above are not populated that way?
- I couldn't figure out a search term to bring up notes to test it.
- The IIIF link worked but it didn't show up as an image (I tested with T-S NS J490)

**Comment by rlskoeser** [comment] 2021-03-08 18:45
> * It's not obvious in the Edit Fragment view that the box for multifragment is supposed to be filled out as "Yes" (I tried it in a test, and it did create a check mark in the right place in the list view, but it wasn't initially clear that this is how that box is supposed to be used. Perhaps a checkbox here would be clearer.

Any value in the multifragment box will result in a checkbox on the list view. Right now only ~10 fragments are being imported with a multifragment value.  The ones that imported have values like: "fol. 2", "middle", "bottom", "Top left", "Top", "right", etc.

> * Filter by Multifragment (Yes/No) didn't work either, perhaps because the boxes referenced in my question above are not populated that way?

You're right! It's not working for me either. Will investigate.

> * I couldn't figure out a search term to bring up notes to test it.

I don't think any of the current data have notes. I suggest adding some test content that you know will be unique to one of them, and then confirm you can find it by search.

> * The IIIF link worked but it didn't show up as an image (I tested with T-S NS J490)

Yep, you're right. Looks like it isn't working in qa because of an http/https mixed content issue. I will investigate and remedy.

**Comment by richmanrachel** [comment] 2021-03-08 20:11
I confirmed that notes are searchable!

So I will change the status now to "tested needs attention" where the issues remaining are:
1) Make filter by multifragment work.
2) Make sure IIIF images appear.

@rlskoeser and I will have a meeting tomorrow to go more in depth on the way multifragments, joins, related documents work. This will address my earlier concern of how to fill out the box labeled multifragment as well as the problems arising from #68.

**Comment by rlskoeser** [comment] 2021-03-10 19:18
Decision made in conversation with @richmanrachel — Fragment model should have a boolean field (instead of current text field) for multifragment to indicate if the shelfmark contains multiple fragments.

**Comment by richmanrachel** [comment] 2021-03-15 15:59
Bad news: the IIIF viewer still isn't working :(

Good news: everything else is!

Feature request: 
1. Can we make the default Text Block shelfmark be the same as whatever fragment we're editing? This will make it less likely that user error accidentally creates a false-join through typing mistakes while trying to edit which text blocks are on the same fragment.
2. Can the list of collections in the side bar be changed to use the abbreviations? It's a lot of text right now, and backend users will know the abbreviations.

**Comment by rlskoeser** [comment] 2021-03-22 21:13
@richmanrachel This one is ready for re-testing again. 
- I switched to a different IIIF viewer, please see if it works for you now. 
- Also, I switched the collection list to use abbreviations as you suggested (much easier to work with, I agree).

**Comment by richmanrachel** [comment] 2021-03-23 18:26
It works! Not sure if there's a way to add rotating the document to be built in here (for ex. this one shows up sideways - CUL Add.3337). 

Two other small things this brings up:
1. I'm not sure if it will be helpful in the backend, but if we can figure out for the front end how to filter by IIIF empty/not empty, that would be lovely. 
2. Can the collections in the sidebar for Fragment List View be re-ordered alphabetically, please? They're much easier to read now, but still difficult to find.

[And @rlskoeser - in general, do you want me to hit "close with comment" at this point, or keep it open until our discussion is complete?]

**Comment by rlskoeser** [comment] 2021-03-23 18:41
I'm hoping we'll be able to add default orientation in future! But not sure how difficult it will be to determine that yet; I don't think we shouldn't tackle it yet. Or are you asking for image rotation support in the viewer?

I agree that the public search should allow users to filter for documents with images available! I don't know if we have a good place to track things like this; future log maybe? I imagine it is already on @gissoo's radar as well.

Good catch on the collections sorting — I think we should revisit that, I don't think I updated it after the last revision to the content model.  I'm not sure what the proper sorting should be, though — we're displaying library & collection abbreviations, so it seems like the sort should match that, but there are a few collections with no abbreviations; if I add library name and collection name as fallback sort options, those show up first because they don't have an abbreviation.  The easiest thing would be if we could add abbreviations or short names for those; if this requires further discussion, let's open a new issue to track it. (It's a trivial change in the code once the decision is made.)

And thanks for asking about closing! In general, I'm fine with keeping issues open while we're discussing things related to them, as long as we can get issues that have passed testing closed before the iteration ends. But let's keep other options in mind too: we can create new issues, shift conversations to slack or add to meeting agendas; and we might want to start documenting ideas that come up during testing somewhere like the future log, too.

**Comment by richmanrachel** [comment] 2021-03-23 18:48
@rlskoeser - if image rotation support is possible, that would be best (because sometimes we want to see scribbles/annotations that aren't at the default angle). 

I'll add discussion about a "Future Log" to our Thursday agenda.

I see re: collections.... I think making sure they all have "abbreviations" (even if it's their name) will work and be analogous to "display name" for languages. I'll double check with Marina.

**Comment by rlskoeser** [comment] 2021-03-23 19:06
@richmanrachel just looked, image rotation isn't available by default. There is a plugin that we can investigate adding later on, I know Gissoo has specific ideas about the functionality that should be available for viewing images on the public site.

I'll go ahead and revise the collection ordering. It might look a little funny until collection abbreviations are added, but I think that's fine.

**Comment by rlskoeser** [comment] 2021-03-24 16:51
@richmanrachel I figured out the right way to handle collection ordering (doesn't require that we set abbreviations now). Please take a look and then go ahead and close this.

**Closed** 2021-03-26 15:12 UTC
Labels: 🗜️ awaiting testing
