### ISSUE TITLE
As a Content Admin, I want a one time import of a document's edit history to start building a history of who has worked on the document and when.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/geniza#111] opened 2021-03-18 18:47 UTC
# testing notes
Once the import has been run, you should be able to visit any Document in the admin interface and click the "history" button to see a record of events for that document:

- the date the document was added to the spreadsheet will be marked
- if there were any major revisions in the spreadsheet, they will be marked
- in any case where more specific information wasn't available, the event will be assigned to "Geniza Lab team"
- the actual time at which the document was moved from the spreadsheet to the database will be marked and assigned to a "script" user

Note that events that occurred prior to moving to the database will list the "date entered" value from the spreadsheet in the change message. This value **may be different** from the date that the event is recorded; that's because we have to fill in an exact day to store it in the database, so missing information will have been auto-filled (e.g. 2017 becomes Jan. 1, 2017).

Try visiting several Documents, and maybe try [some of the PGPIDs listed in this doc](https://docs.google.com/document/d/1mo8XDA1WMmwgOReGunEFXeG_vMTCBwVtWO5pA3PtNUc/edit?usp=sharing) since they are known to have complex edit histories.

# dev notes
**Is your feature request related to a problem? Please describe.**
This corresponds to the "legacy input date" information in the spreadsheet. Without this issue, information about when records were created and edited would be lost, because the database would only "know" about records starting from the day on which they were imported into the new database. We want a more complete record that incorporates the edit history while documents were in the old metadata spreadsheet.

See also #112 which depends on this issue and handles displaying this information on the document edit page.

**Describe the solution you'd like**
- A Django admin log entry that marks a creation event is created to mark the "first input date" listed in the spreadsheet.
- If necessary, a Django user account is created to represent the person who first input the document, so that the creation record can be tied to that account. The user account should be marked as non-active, because this person will not log in to the admin site (it's only for representation purposes).
- If there are subsequent semicolon-delimited entries in the "legacy input date" field, a Django admin log entry that marks an edit event should be created for each of them.
- If necessary, Django user accounts should be created to represent the people who made subsequent edits, as above.

an example of a case with two entries; a document that was first input by Marina in 2018 and updated by Alan in 2020:
![Screen Shot 2021-03-18 at 11 11 33 AM](https://user-images.githubusercontent.com/4924494/111680494-ab450b00-87f8-11eb-9f93-893a33e48fbf.png)

**Additional context**
As noted by Alan, this field has some quirks. Some entries will appear as:
![Screen Shot 2021-03-18 at 11 11 01 AM](https://user-images.githubusercontent.com/4924494/111680072-38d42b00-87f8-11eb-8312-cd2f880a444e.png)
...meaning that an unknown person first entered the record sometime in 2017, and alan later updated it in december 2020. 

@mrustow promised to try to manually update such cases where more information is known (e.g. the person and perhaps month), but we will likely never have exact day information. It seems like the simplest option in such cases is to just create the log entry for the first day of the month, perhaps with an additional note in the entry that the exact date wasn't known (if this is possible).

**Comment by thatbudakguy** [comment] 2021-04-07 20:45
bumping to 5 per @rlskoeser

**Comment by richmanrachel** [comment] 2021-04-09 21:05
@rlskoeser - I don't think we can actually search by PGP ID to check the ones Nick suggested. Marina and I are wondering if the PGP ID is meant to be staged out in a sense, or whether if it continues to be the best way for us to do data work if we want to make it more prominent.

**Comment by richmanrachel** [comment] 2021-04-09 21:08
But it does seem to work really well!

**Comment by rlskoeser** [comment] 2021-04-09 21:08
Ha, you're right, PGP ID isn't searchable. We should probably fix that. And maybe we should display it on the list view, if we're going to refer to it.

But this also sounds like something we should discuss!  We need to preserve PGP ID at minimum for redirects from the old site to the eventual new one, but we also need a way to reference unique Documents since shelfmark isn't always sufficient and may not be stable.

**Comment by rlskoeser** [comment] 2021-04-09 21:09
@richmanrachel I could quickly make PGPID searchable if it would help with testing

**Comment by richmanrachel** [comment] 2021-04-09 21:20
@rlskoeser - I think that displaying and making the PGP ID searchable is an easy decision that we can go ahead and act on. But happy to raise in a meeting as well so we can talk about its role in the future. I agree it might be more stable than shelfmarks in certain situations.

**Comment by richmanrachel** [comment] 2021-04-14 19:46
Confirmed - it's great! Closing :)

**Closed by richmanrachel** 2021-04-14 19:46 UTC
Labels: 🆕 enhancement, 🗜️ awaiting testing
