### ISSUE TITLE
As a content editor, I want to create, edit, filter and search documents so that I can add/edit information on documents in the database and find pertinent documents.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#68] opened 2021-02-09 18:29 UTC
### Testing Notes
**List display:**
- [x] Ensure that all fields that you want visible are available
- [x] Test that Documents are searchable by:
  - [x] shelfmark
  - [x] tag
  - [x] description
  - [x] PGP team member who input data
- [x] Test that results for filtering by the following fields operate properly:
  - [x] document type
  - [x] language
  - [x] extent label
  - [x] multifragment

**Edit**
- [x] Test that changes to a document through the edit display are saved and reflected in the list view.
- [x] Test that read only fields are displayed and not editable
- [x] Test that text blocks for associated fragments are listed and can be updated
- [x] Test that you can't add unknown for a probable language
- [x] Test that you aren't allowed to set the same language+script as both language and probable language
- [x] Test that you aren't allowed to set unknown language+script as probable language
- [x] Test that multiple text blocks on the same shelfmark don't result in repeated shelfmark in document combined shelfmark
- [x] Test setting text block order and confirm that join shelfmark follows the specified order

-----

## dev notes

revisions after testing:
- [x] switch language and probable language to autocomplete
- [x] fix language/probable language validation
- [x] add help text for language and probable language (to be supplied by the team)
- [x] fix document shelfmark so it includes unique shelfmarks in order
- [x] add multifragment text field
- [x] make extent filter empty/not empty
- [x] add empty/not empty multifragment filter

**Fields**
Provide a list of the fields and entities to be included on this model.
- Fragments (entity)
- description
- side
- text-block
- Type (entity)
- Tags (entity)
- language
- Footnotes for edition and translation (entity)
- notes
- input by
- date entered

**List Fields**
Which fields should be included on the django admin list view?
- shelfmark
- description
- type
- tags
- language
- text-block (boolean)
- edition

**Edit Fields**
Which fields should be editable via django admin view? Please list them in the order you want them to appear. Indicate which fields are optional, and any fields that should be displayed but not editable.
- shelfmark (read only) at least one, possibly more
- historical shelfmark (read only)
- side (to indicate recto/verso)
- Image thumbnail (optional)
- type (optional)
- language
- description
- tags (optional)
- edition (optional)
- translation (optional)
- notes (optional)
- text-block (optional)
- Legacy input by (read only)
- Legacy date entered (read only) 

**Search Fields**
Which fields should be searchable in the django admin list view?
- description
- tags
- shelfmark
- edition
- input by

**Default sort**
- Shelfmark

**Filters**
Which fields should be used for list filters?
- Type
- language
- Text-block 

**List Fields (optional)**
Which fields (if any) should be editable on the django admin list view?
None.

**Related models**
List any directly related models (database tables) that would be helpful to edit when on the same page when editing this one.
    •    Fragment model

**Additional context**
Add any other context about the model or database here. Include a link to a database diagram if one is available.

-----
**Old version**
~List view fields (in order):~
~- Shelfmark (current) **(searchable)**~
~- Shelfmark historical **(boolean: does it have a historical shelfmark?)**~
~- Library (abbreviation) **(filter)**~
~- recto/verso **(filter)**~
~- type **(filter)**~
~- tags **(filter & searchable)**~
~- language/script **(filter)**~
~- description **(searchable)**~
~- editor **(searchable)**~
~- translator **(searchable)**~
~- link to image/image **(thumbnail, IIIF),**~
~- multifragment **(boolean: is it part of a multifragment?)**~
~- text-block **(boolean: is it assigned text-blocks?)**~
~- Input by **(searchable)**~
~- date entered **(searchable)**.~

~None editable in the list view.~
~Filter: shelfmark (historical), Library, Recto/verso, type, tags, language/script, multifragment, text-block~
~Searchable: Shelfmark (current), tags, description, editor, translator, input by, date entered.~

**Comment by sluescher** [comment] 2021-02-16 01:14
Should I switch this out with the story we looked at today?

**Comment by rlskoeser** [comment] 2021-02-16 14:39
@sluescher yes, since it's already written up that would be great.

**Comment by sluescher** [comment] 2021-02-16 14:50
I have updated it!

**Comment by sluescher** [comment] 2021-02-25 21:20
Added fields in today's meeting (2/25)

- language (probable), optional, filter

Help text to come

Not in django admin list view

**Comment by thatbudakguy** [comment] 2021-02-25 21:22
- "language" and "probable language" are mutually exclusive sets
- "unknown" is an option for "language" but not "probable language"

**Comment by kmcelwee** [comment] 2021-03-03 17:28
### Testing Notes
**Document Admin List display:**
- [ ] Ensure that all fields that you want visible are available
- [ ] Test that Documents are searchable by:
  - [ ] shelfmark
  - [ ] tag
  - [ ] description
  - [ ] PGP team member who input data
- [ ] Test that results for filtering by the following fields operate properly:
  - [ ] document type
  - [ ] language
  - [ ] extent label

**Document Admin Edit display**
- [ ] Test that changes to a document through the edit display are saved and reflected in the list view.

**Fragment Admin List display**
- [ ] Ensure that fields that you want visible are available
- [ ] Test that fragments are searchable by:
  - [ ] shelfmark
  - [ ] old shelfark
  - [ ] notes
- [ ] Test that results for filtering by the following fields operate properly:
  - [ ] collection
  - [ ] Is a multifragment
  - [ ] Has a url

**Fragment Admin Edit display**
- [ ] Test that changes to a fragment through the edit display are saved and reflected in the list view.

**Data import**
- [ ] Go through random samples from the following models to ensure that the information from the metadata and ontology spreadsheets are properly reflected in the admin interface:
  - [ ] documents
  - [ ] languages
  - [ ] document type
  - [ ] libraries

**Comment by richmanrachel** [comment] 2021-03-04 17:06
List Display (Chrome Browser):
- The immediate difficulty I have is that I don't think I'm seeing all of the columns. When I play around with browser size, more appear, but there's no indication (by a scrollbar at the bottom, for example), that I'm not seeing all fields. Closing the side bar did seem to open it for me, but it would still be helpful to have a way to access additional columns when the window is smaller. 
- I love the multiple filter options, but perhaps they could be drop downs like the "Action" button, so as to take up less space on the right hand side and be more accessible. 
- The search does properly capture information from tags, descriptions, and input person. But I don't see how to search specifically for one vs. the other. For example, when I search "illness," I get a mixture of documents that have been tagged with that label as well as ones where it appears in the description. I'm not sure how crucial it is to differentiate, but I'm not sure if this counts as closing out your tick-boxes above.
- If by "extent label" you mean filtering by multifragment or not, it does not work.
[I'll check edits later]

**Comment by richmanrachel** [comment] 2021-03-04 18:01
Edits:
- When I added a fake text block, it makes the shelfmark in the main list view look like a join.

**Comment by richmanrachel** [comment] 2021-03-04 22:15
- Oops, editing my earlier comment about extent label. It does work, but not at all in the way I was expecting. It's not very useful to filter by what the extent is called. It would be more helpful to do a more general sort in the multifragment column to filter between which documents are or are not multifragments. 
- We will definitely have to do significant manual labor to fix the existing multifragments. Am I correct that this section was populated with whatever shelfmarks had letters at the end?
- Our error with Bodl. MS Heb. f 56/16 is probably because it's listed with 7 other nearby shelfmarks as a join. Looking at the images on FGP it does appear to be part of a multipage pamphlet/book. 
- Fail: I could add Judaeo-Arabic to language and probable language.

**Comment by rlskoeser** [comment] 2021-03-08 17:49
@richmanrachel thanks for all the great testing feedback. Lots here, quoting your comments to give context to my answers.

> * The immediate difficulty I have is that I don't think I'm seeing all of the columns. When I play around with browser size, more appear, but there's no indication (by a scrollbar at the bottom, for example), that I'm not seeing all fields. Closing the side bar did seem to open it for me, but it would still be helpful to have a way to access additional columns when the window is smaller.

@richmanrachel what kind of machine are you using? Are you on a laptop with a smaller screen? This may be one of the limitations of django admin.  I just checked on my machine, and there is a scrollbar but it doesn't display until you get to the bottom of the results.

> * I love the multiple filter options, but perhaps they could be drop downs like the "Action" button, so as to take up less space on the right hand side and be more accessible.

There are third-party libraries that do this, but we've run into maintenance problems with that in the past, so I'd prefer to avoid that. We prefer not to do a lot of customization on the django admin interface so we can focus our efforts on the data and public interface.

> * The search does properly capture information from tags, descriptions, and input person. But I don't see how to search specifically for one vs. the other. For example, when I search "illness," I get a mixture of documents that have been tagged with that label as well as ones where it appears in the description. I'm not sure how crucial it is to differentiate, but I'm not sure if this counts as closing out your tick-boxes above.

The admin search is fairly "dumb" — it searches across all the fields we have configured, and it will match any of them. For testing and sign off it doesn't matter to differentiate as long as you're able to find records by content in any of the fields that should be searchable.

> * If by "extent label" you mean filtering by multifragment or not, it does not work.

There is an extent label filter under the language filter on the right side. This is populated by information in the **Text-block (optional)** field in the metadata spreadsheet.  (Remember, we named it extent label because we're using "Text Block" as the name for the part of a document on a single fragment.)

> Oops, editing my earlier comment about extent label. It does work, but not at all in the way I was expecting. It's not very useful to filter by what the extent is called. It would be more helpful to do a more general sort in the multifragment column to filter between which documents are or are not multifragments.

Fragments have a multifragment field and the list view includes an indicator for multifragment as well as a boolean filter. 

Is the extent label filter not useful?

> We will definitely have to do significant manual labor to fix the existing multifragments. Am I correct that this section was populated with whatever shelfmarks had letters at the end?

I'm not sure from your notes if you're confusing multifragment and extent label / text block, but none of these are populated from information in the shelfmark. The fragment multifragment information is coming from the **Multifragment (optional)** field in the metadata spreadsheet. 

> Our error with Bodl. MS Heb. f 56/16 is probably because it's listed with 7 other nearby shelfmarks as a join. Looking at the images on FGP it does appear to be part of a multipage pamphlet/book.

That's interesting. I think you all have enough data that we should implement a different search solution for documents so we don't have this problem, but I'd like to track that work under a separate story. (We've done this before; the django admin search is known for being inefficient since it's a generalized solution not tuned for a particular porject).

> Fail: I could add Judaeo-Arabic to language and probable language.

Whoops! Thanks for catching that.

> When I added a fake text block, it makes the shelfmark in the main list view look like a join.

Right — this is expected behavior. Adding a new text block means you have associated this document with a second fragment, therefore it is a join, which is how we display the document shelfmark.

**Comment by richmanrachel** [comment] 2021-03-08 20:34
Okay, updating the checkmarks above as the extent label filter technically works. However it doesn't provide any value from my point of view. I will get an opinion about this from @mrustow on Thursday morning.

@rlskoeser - yes, I only have a laptop with a smallish screen (a 2016 Macbook with a 12" screen). I think most students who will be working as RAs in the lab, especially undergrads, will also mostly be working on smaller laptops without additional screens. I can live with the layout as is, it's just a bit of a challenge if I want to toggle between the backend and another application (because I can't downsize to have it side by side). But I agree that focusing on layout functionality for the front end is ultimately more important.

I'll start thinking about how to write a user story for searching joined shelfmarks.

So I think the only direct issue in this story that requires a fix is making sure you can't add the same language and probable language.

**Comment by rlskoeser** [comment] 2021-03-10 20:52
@richmanrachel follow up based our discussion about screen real estate in django admin. I was using a tabular inline for the text block editing, but another option is a stacked inline. Here are screenshots so you can compare the two:

![Screen Shot 2021-03-10 at 3 49 14 PM](https://user-images.githubusercontent.com/691231/110695846-5bdb5b00-81b8-11eb-86df-9dc7de6e705e.png)
![Screen Shot 2021-03-10 at 3 49 31 PM](https://user-images.githubusercontent.com/691231/110695870-63026900-81b8-11eb-9fea-3f6818aeeb34.png)

In the stacked inline, we could configure some fields to be on the same row so it doesn't take quite as much space up vertically.

Do you want to confer with Marina and let me know if you want to switch to the stacked inline?

**Comment by richmanrachel** [comment] 2021-03-11 14:47
@rlskoeser - Marina and I agree we should keep it inline, because it would be hard to keep track of comparisons in the stacked format.

**Comment by richmanrachel** [comment] 2021-03-11 15:16
@rlskoeser 
Extent label: empty/filled is a huge improvement, thank you!

And all other tests worked now!!!

**Closed by richmanrachel** 2021-03-11 15:16 UTC
Labels: 🗜️ awaiting testing
