### ISSUE TITLE
As a content editor, I want to be able to filter/search within the “needs review” field of the list of items "awaiting review," so that I can more efficiently review issues of the same type in batches (docs that need fixes to description, shelfmark, etc).

### ISSUE THREAD

**Issue by mrustow** [Princeton-CDH/geniza#114] opened 2021-03-25 14:31 UTC
**Fields**
Provide a list of the fields to be included on this model. 
- field 
- field

**List Fields**
Which fields should be included on the django admin list view?
- field
- field 

**Edit Fields**
Which fields should be editable via django admin view? Please list them in the order you want them to appear. Indicate which fields are optional, and any fields that should be displayed but not editable.
- field
- field 
- field (optional)
- field (read only)

**Search Fields**
Which fields should be searchable in the django admin list view?
- field
- field 

**Default sort**
Which field should be used for initial sorting?

**Filters**
Which fields should be used for list filters?

**Date Hierarchy (optional)**
Which field (if any) should be used for date hierarchy? (must be a date object)

**List Fields (optional)**
Which fields (if any) should be editable on the django admin list view?

**Field translation (optional)**
Which fields (if any) do you want to provide in multiple languages?

**Related models**
List any directly related models (database tables) that would be helpful to edit when on the same page when editing this one.

**Additional context**
Add any other context about the model or database here. Include a link to a database diagram if one is available.

**Comment by mrustow** [comment] 2021-03-25 14:32
@rlskoeser which of the fields do we actually need to specify for this?

**Comment by rlskoeser** [comment] 2021-03-25 14:58
@mrustow if you give us a list of keywords that you want available for filtering within the `needs_review` field (and develop a workflow to make sure your team uses those keywords), we could write a custom filter that would do this.  However, this approach would require us to update the list of terms in the code whenever you want to add a new item to the list, which is obviously not ideal for anyone.

One solution that other project teams have used is to develop a list of codes or keyword terms that you can search for without getting irrelevant matches for terms used in other fields (e.g., could be something like NEED_DESCR or NEED_SHLFMRK).

I've made the needs review field search able in admin. Would you try adding some test review notes and using the existing needs review filter & keyword search to see if that gets you the functionality you need?

**Comment by rlskoeser** [comment] 2022-01-28 14:48
duplicate of #383 and also probably addressed/improved by field-based advanced saerch

**Closed by rlskoeser** 2022-01-28 14:48 UTC
