### ISSUE TITLE
Unable to delete documents due to lack of permissions to delete log entry

### ISSUE THREAD

**Issue by richmanrachel** [Princeton-CDH/geniza#476] opened 2021-12-27 22:41 UTC
**Describe the bug**
Marina created a test document in the regular admin site and was unable to delete it, getting this error message:
![image](https://user-images.githubusercontent.com/68028846/147511565-2f55f3f8-4496-4c1e-9023-ca83f79ef724.png)

Rachel then tried, and got the same error message. Rachel went into the Users section of the admin site and specifically added permission to delete log entries to her account, but still received the same error. 

**To reproduce**
1. Go to PGPID 35058
2. Click on Delete
3. See error

**Expected behavior**
A warning message appears, but Super Users/Content Admin should be able to delete.

**Device information**
 - Rachel was on MacBook Air 2021, and Chrome browser 
 - Site version [0.7.0]

**Comment by blms** [comment] 2022-01-03 22:03
Duplicate of #371

**Closed by blms** 2022-01-03 22:03 UTC
