### ISSUE TITLE
Revise document title for joins

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/geniza#493] opened 2022-01-05 22:36 UTC
@rlskoeser and @gissoo - Marina and I just met and we agree that we need to have the full set of shelfmarks in the title (especially if the join is only 2, we might be flexible about 3+). 

Although I initially thought it would be repetitive to have the shelfmark in the title and listed again below, Marina has convinced me that this repetition is productive as it's "easier on the eyes" and will help scholars keep track of this most crucial data point.

_Originally posted by @richmanrachel in https://github.com/Princeton-CDH/geniza/issues/460#issuecomment-1006126981_

**Comment by gissoo** [comment] 2022-01-12 01:27
@rlskoeser @richmanrachel @mrustow I think this might make sense for two – I don't quite agree that it's easier on the eye, but having more specific examples and context would be helpful to see the issue – reading this, my perception is that a sweet spot for the 3+ shelfmarks is if they appeared as a subtitle right below the doc title in the search results – there really shouldn't be two lines of document title. Can you say more about "will help scholars keep track of this most crucial data point."? Are you saying this because it's not appearing on the search results? If so, then having them appear right below the title might make them more readable than as the document title

**Comment by blms** [comment] 2022-01-25 16:39
> Ideally long shelfmarks within joins like the above (however or wherever they end up appearing) should be broken not in the middle of the shelfmark but either before or after the + : 
> Bodl. MS heb. f 34/41
> + Bodl. MS heb. f 34/40
> + Bodl. MS heb. f 34/39
> 
> or 
> 
> Bodl. MS heb. f 34/41 +
> Bodl. MS heb. f 34/40 +
> Bodl. MS heb. f 34/39
> 
> @richmanrachel do you have a preference between those two options? I _think_ I prefer the first one.

_Originally posted by @mrustow in https://github.com/Princeton-CDH/geniza/issues/532#issuecomment-1021369240_

**Comment by blms** [comment] 2022-01-25 16:40
>  <img width="312" alt="Screen Shot 2022-01-19 at 6 42 20 PM" src="https://user-images.githubusercontent.com/44615389/150236029-33657467-3ea4-4d72-bbc4-cab7b550666b.png">

_Originally posted by @gissoo in https://github.com/Princeton-CDH/geniza/issues/532#issuecomment-1016972071_

**Comment by blms** [comment] 2022-01-25 16:45
Actually these might be two separate issues—the one referenced in the original description seems to be about the document detail page, and the rest is about the way a document title will appear in search results (e.g. the + indicator for joins, the above screenshot, etc).

In a sense the two questions are, with special consideration for large joins with many shelfmarks:

1. How should joins be displayed in the title header of the document detail page?
2. How should joins be displayed in search results? (subtitle, + indicator, etc.)

**Comment by richmanrachel** [comment] 2022-01-25 16:47
@blms - thank you for redirecting the conversation here. I agree that the issue is about the titles and should be discussed here. 
1) I'm open to different fonts or a visual indication that there is more than one document.
2) I think we need the full list of joins as part of the header for search results. 

@mrustow - what were your comments regarding changing the font type to include all elements of the join in the title, and/or implementing a new design where the shelfmark stays stable on the side as you scroll?

**Comment by richmanrachel** [comment] 2022-01-25 16:53
Quoting @mrustow from #532 
> Ideally long shelfmarks within joins like the above (however or wherever they end up appearing) should be broken not in the middle of the shelfmark but either before or after the + :
Bodl. MS heb. f 34/41

Bodl. MS heb. f 34/40
Bodl. MS heb. f 34/39
or

Bodl. MS heb. f 34/41 +
Bodl. MS heb. f 34/40 +
Bodl. MS heb. f 34/39

@richmanrachel do you have a preference between those two options? I think I prefer the first one.

- I think I would go with the second, since the plus signs are our main way of signifying joins and it would keep it more consistent with the desktop version.

**Comment by blms** [comment] 2022-01-26 19:41
@richmanrachel 
> 1. I'm open to different fonts or a visual indication that there is more than one document.

Did we have a design already for that, or is this something @gissoo would need to come up with? And should this be MVP, or do we want to settle on something simpler for MVP like just displaying the full set of shelfmarks in the same font?

This is what PGPID 5626 looks like now, so likely we'll want to adjust it somehow before MVP:

<img width="637" alt="Screen Shot 2022-01-26 at 2 38 44 PM" src="https://user-images.githubusercontent.com/7234006/151234461-e282692d-8946-459e-bc47-09765895ba35.png">

> 2. I think we need the full list of joins as part of the header for search results.

OK—did we decide this should be post-MVP? And does @gissoo agree with the proposed solutions (listing all shelfmarks in search results, separated by plus sign)?

**Comment by rlskoeser** [comment] 2022-01-26 21:07
We are actually already displaying all the shelfmarks in the search results — which I guess is not the design. I noticed at some point the discrepancy between search and document detail but forgot to follow up.

As a minimum first step, @blms can we wrap individual shelfmarks in a tag and add a `white-space: nowrap` ? this should be done both in `document_result.html` and `document_detail.html` — but it looks like that means we won't be able to use the `shelfmark` property on `Document` anymore.

**Comment by richmanrachel** [comment] 2022-01-26 21:11
@blms - I think the current design is okay for MVP. While it bothers me, I don't think it's worth designing something new and holding up progress.

**Comment by gissoo** [comment] 2022-01-27 21:35
@blms, since we have changed our minds about this a few times no design work was taken into account for it. 
At our last meeting, Marina agreed that what we have is okay for MVP – It's not ideal but it's not breaking anything, and there are higher priorities for MVP and I agree with leaving it as is for now. I'm not sure what the MVP solution would be for the document detail page: so it seems like in the document detail page we should also place all the shelfmarks as part of the page title to make it consistent with search results, correct? That is fine with me for now.

Note: I also agree with Rachel about the second option from Marina's comment – the plus sign is more clear.

**Comment by blms** [comment] 2022-01-27 21:39
@gissoo Sounds good, thank you for weighing in!

@rlskoeser Should we remove this issue from MVP and move the revised title to #547? (I know that was what this issue was originally about, but the discussion here seems more useful post-MVP)

**Comment by rlskoeser** [comment] 2022-01-27 21:44
@blms that sounds like a good solution to me!

**Comment by kseniaryzhova** [comment] 2022-11-17 19:18
@rlskoeser I think what we have (full display of all shelfmarks in joins in search results, and document detail page) is exactly what Marina wants. Closing!

**Closed by kseniaryzhova** 2022-11-17 19:18 UTC
