### ISSUE TITLE
As a content editor, I want to download any data sets created through filters so that I can work on a subset outside of the database.

### ISSUE THREAD

**Issue by sluescher** [Princeton-CDH/geniza#67] opened 2021-02-09 13:34 UTC

**Comment by rlskoeser** [comment] 2021-03-03 22:01
We're interpreting this as an admin download of document data in CSV format that can be generated from the document list (whole or filtered) in the admin site. Please provide the list of fields/information you'd like included in the download.

**Comment by rlskoeser** [comment] 2021-03-10 15:31
@richmanrachel is this meant to be an admin download for working with the data, or the CSV that we'll make available to the current PGP site so it will stay current once we move the data from the spreadsheet to database?

If it's the first, we need more details about what fields should be included. If it's the second, let's revise the story to make it clearer. (And if it isn't, let's write and add that story because we need that too!)

**Comment by richmanrachel** [comment] 2021-03-10 19:40
@rlskoeser - It's the first one. As for what fields should be included... is there any way for the content editor to pick before each download? I imagine that every researcher will want a slightly different combination. 

And I'll add the database backup version to my list of stories that need to be developed.

**Comment by rlskoeser** [comment] 2021-03-10 19:47
> is there any way for the content editor to pick before each download? I imagine that every researcher will want a slightly different combination.

@richmanrachel That might make sense for the public download, but the admin download needs to be simpler than that. Let's set it up to include everything (within reason) that you think people will want, and researchers can just ignore or remove the things they don't care about

**Comment by rlskoeser** [comment] 2021-05-27 13:33
duplicate of #121 (and also possibly #189 and #190)

**Closed by rlskoeser** 2021-05-27 13:33 UTC
Labels: ❓ question, 🆕 enhancement
