### ISSUE TITLE
As a content editor, I want Person-Person relationship types visually sorted into their categories in the admin form, so that I can select them at a glance.

### ISSUE THREAD

**Issue by blms** [Princeton-CDH/geniza#1390] opened 2023-06-13 18:43 UTC
### testing notes (QA)

On the [QA site admin](https://test-geniza.cdh.princeton.edu/admin), create or edit a Person entry.

- [x] Under "Related People", the dropdown of types of relationships (the one labeled "Relation") should be sorted into categories such as business and property, extended family, etc.

### dev notes

optgroup with model choice field

**Comment by kseniaryzhova** [comment] 2023-08-30 16:49
@blms Noticed that I cannot add related documents from the person page, which seems like an issue if someone is working from their own personal archives and not going through the documents separately. Is this expected behavior or a bug?

![image](https://github.com/Princeton-CDH/geniza/assets/105385128/0a1498f0-1fe8-48a0-a30b-fc1be5e33cc0)

**Comment by kseniaryzhova** [comment] 2023-08-30 16:56
@blms Re: my comment on adding the additional people-to-people relationships (possibly the same as, not to be confused with). I can add the relationships, but I do not see a way to add the subheadings that would group these automatically. Otherwise, for the existing relationship, it does group automatically in the dropdown.

**Comment by kseniaryzhova** [comment] 2023-09-05 15:41
@blms ok, closing! Will update the other user stories once I've discussed with MR.

**Closed by kseniaryzhova** 2023-09-05 15:41 UTC
Labels: 🆕 enhancement, ⚠️ tested needs attention, performant

**Comment by rlskoeser** [comment] 2023-09-08 17:44
> The problem here is that we don't know what the reverse relationship should be, in other words if someone says "Parent" we don't have a system to have the other person say "Child". I wonder if it would make sense to have these reverse relationships created automatically—would love @rlskoeser's input here if this is sensible, since this is some advanced Django modeling! It might be a separate user story. (Something like "As a content admin I want the reverse relationships between people automatically populated, so I do not have to enter each relationship twice")

Auto-generating reverse relationships seems like a bad idea to me - more complicated and hard to make sure everything stays in sync.  We get the reverse lookup automatically if we want it, right? Can you leverage that somehow?

One thought is to add an optional reverse label for relationships that have reverse names (like parent/child); and/or a flag to mark relationships as symmetric, where label can be used both directions (e.g. spouse or friend).

Can you share some links to anything on the test site where I could see what this currently looks like, and help me think through by way of specific examples?

**Comment by blms** [comment] 2023-09-08 17:52
> Auto-generating reverse relationships seems like a bad idea to me - more complicated and hard to make sure everything stays in sync. We get the reverse lookup automatically if we want it, right? Can you leverage that somehow?

Yes, that's what I was considering with the non-editable list of reverse lookups. (If I'm understanding correctly)

> One thought is to add an optional reverse label for relationships that have reverse names (like parent/child); and/or a flag to mark relationships as symmetric, where label can be used both directions (e.g. spouse or friend).

That makes sense, since there are some where the label would be the same in both directions.

> Can you share some links to anything on the test site where I could see what this currently looks like, and help me think through by way of specific examples?

I just added one example, but it might help for @kseniaryzhova to add more (I think they got wiped with the solr replicate run):
https://test-geniza.cdh.princeton.edu/admin/entities/person/2/change/

Copying from slack: One possibility I have been considering is having both directions of the relationship labeled within a single through model instance. It’s less ambiguous that way anyway (right now it’s a little unclear who is whose parent, for example). But I’m not 100% sure about the language to use to clarify which person each refers to! (i.e. having `from_person`, `to_person`, and `relation` it’s ambiguous which direction the relation refers to. so maybe it needs a `from_relation` and a `to_relation` instead)

**Comment by rlskoeser** [comment] 2023-09-08 18:02
I think we may be saying the same thing two different ways. I'm not sure from/to is meaningful enough here (although the naming in the data model isn't as important as how you display in admin and public sites for the people who need to work with and read the information).

Is there any person display page yet, or only the admin?  Would a draft / admin-only person display page help you all think through the data and how to represent it?  It's hard to think through such a generic example.  

Could you display the reverse relationships without making them editable? How much would that help?

If you make the relationship symmetric, does it look exactly the same on both sides? Will you be able to tell which person is the parent and which the child in the relationships that are not named the same way in both directions?

One way to think through this might be to get a list of some specific cases from the team that include symmetric and asymmetric relationships and then you can test out how to model them so you can get the information you want (both for admin and public site).  It sounds like one thing you need to figure out is how to determine which person is which if the relationships that have different labels going the other direction.  (Or is this only a problem if you turn off the asymmetric flag?)

**Comment by blms** [comment] 2023-09-08 18:15
Thank you @rlskoeser. @kseniaryzhova let's see if we can get a small list of specific examples to help determine exactly what this should look like.

To answer your questions:

> Is there any person display page yet, or only the admin? Would a draft / admin-only person display page help you all think through the data and how to represent it?

Only the admin right now, but there is a [design for the display page](https://github.com/Princeton-CDH/geniza/assets/7234006/2c6e4a17-b628-4cfd-9e07-2a25cecf7246). It's not specific about the relationships, because those are actually intended for a future public feature, a network graph of all people and their relationships. (A catch-22 because our designer needs some data to start designing it!)

> Could you display the reverse relationships without making them editable? How much would that help?

I've proposed that as well and I'm curious what the team thinks of that!

> If you make the relationship symmetric, does it look exactly the same on both sides? Will you be able to tell which person is the parent and which the child in the relationships that are not named the same way in both directions?

That's exactly the problem as far as I can tell, it would be ambiguous if we turn on `symmetrical=True`, since the same label would appear on both pages. But if we do implement two labels, one for each direction, we can actually just turn `symmetrical` back on. So that does seem like the ideal solution to me, as long as we can display those fields in a way that makes it clear which direction each label refers to.

**Comment by rlskoeser** [comment] 2023-09-08 18:23
I think I'm starting to wrap my head around this... it seems like making the foreignkey symmetrical will mess up any relationships that are directional, because you won't be able to tell which person has which role (they will both have both?) - but you should be able to test this and determine. Keeping it asymmetrical is more of a pain for editing (esp. for symmetrical relationships) since it won't be obvious which person to add the relationship to, but at least if you can display them the editors will be able to see whether or not a relationship exists.

Maybe you could implement a quick admin-only (for now) version of that person page mockup and add the relationship label to the name as a way of helping everyone see how the relationships will display.

Side note: why do you need a whole column for the person link in admin? It seems like it takes up a lot of space. Is the ✏️ icon not good enough?

**Comment by blms** [comment] 2023-09-08 18:38
Thank you, that's helpful @rlskoeser! Great point about the symmetrical foreign key. I'll see if I can do a quick and dirty version of the design implementation with the addition of relationship label.

> Side note: why do you need a whole column for the person link in admin? It seems like it takes up a lot of space. Is the ✏️ icon not good enough?

Good point, the edit icon should be sufficient.
